server:
  port: 8080

scheduled:
  cron: "*/10 * * * * *"

taskShouldBeRemovedOlderThan: 2022-05-02T20:18:00.000


#Database stuff
spring:
  datasources:
    initialize: false
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:database
    username: sa
    password: password
    driverClassName: org.h2.Driver
  mvc:
    date-format: iso
